name: neurograph
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase packages - stable working versions
  firebase_core: ^3.15.2  # Latest stable version
  firebase_auth: ^5.3.1   # Latest stable version (not beta 6.0.0)
  cloud_firestore: ^5.6.8
  firebase_ml_model_downloader: ^0.3.3
  
  # Other dependencies
  flutter_dotenv: ^5.1.0
  http: ^1.4.0
  uuid: ^4.4.0
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.8
  audioplayers: ^6.5.0
  path_provider: ^2.1.3
  permission_handler: ^12.0.1
  video_player: ^2.8.3
  chewie: ^1.7.5
  flutter_svg: ^2.0.10
  record: ^6.0.0
  http_parser: ^4.0.2
  tflite_flutter: ^0.11.0
  image: ^4.5.4
  flutterfire_cli: ^1.3.1
  image_picker: ^1.0.4

# Override only the problematic platform interface
dependency_overrides:
  firebase_core_platform_interface: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/neuron_background.png
    - assets/audios/
    - assets/images/
    - assets/videos/MeanderTutorialVideo.mp4
    - assets/videos/SpiralTutorialVideo.mp4
    - assets/images/logo.png
    - assets/images/backgroundN.png
    - assets/images/background.png
    - assets/images/profile.png
    - assets/images/spiralCircle.svg
    - assets/images/spiralSquare.svg
    - .env