// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMeeueW8eUCWC3SRH0gyK40CMw27npbjg',
    appId: '1:612591553796:web:3e53d239e6b6a63b781451',
    messagingSenderId: '612591553796',
    projectId: 'neurograph-6c156',
    authDomain: 'neurograph-6c156.firebaseapp.com',
    storageBucket: 'neurograph-6c156.firebasestorage.app',
    measurementId: 'G-0TCZBWGFTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDacVQi97nB-74TiFIa0psZldIp423awx0',
    appId: '1:612591553796:android:4aa8983d1edf9ba7781451',
    messagingSenderId: '612591553796',
    projectId: 'neurograph-6c156',
    storageBucket: 'neurograph-6c156.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWqsFji07GM2HPuqZcgFRV2GmMDSoaBEo',
    appId: '1:612591553796:ios:6fd2c2b8981c3776781451',
    messagingSenderId: '612591553796',
    projectId: 'neurograph-6c156',
    storageBucket: 'neurograph-6c156.firebasestorage.app',
    iosClientId: '612591553796-8hlm4o5rlmrei8sqgv45hg2h0snc67il.apps.googleusercontent.com',
    iosBundleId: 'com.example.neurograph',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWqsFji07GM2HPuqZcgFRV2GmMDSoaBEo',
    appId: '1:612591553796:ios:6fd2c2b8981c3776781451',
    messagingSenderId: '612591553796',
    projectId: 'neurograph-6c156',
    storageBucket: 'neurograph-6c156.firebasestorage.app',
    iosClientId: '612591553796-8hlm4o5rlmrei8sqgv45hg2h0snc67il.apps.googleusercontent.com',
    iosBundleId: 'com.example.neurograph',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMeeueW8eUCWC3SRH0gyK40CMw27npbjg',
    appId: '1:612591553796:web:01feb0ec7aaec7b7781451',
    messagingSenderId: '612591553796',
    projectId: 'neurograph-6c156',
    authDomain: 'neurograph-6c156.firebaseapp.com',
    storageBucket: 'neurograph-6c156.firebasestorage.app',
    measurementId: 'G-YE896DCFW5',
  );
}
